# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14c872808e8f5cfcd114a37e1d33ebf26aa9418ead4490054d76580356eb21d2b39014d8c4c87d47b9701e0e6c684c7ef0fbba0226b56ca2d7b8e855c56a8538

test:
  secret_key_base: eb2c5e8e0ea4c74a60321b8f1f5d5fc4d1d51e3d0a2e7c4ede8d534862d0e846b26ec40110339c3118795e8d2d0235f3a88b097b4dffdb3a6e6b10ba14185d8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
